version: '2'
services:
  eltragateway-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/EltraGateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=EltraGateway
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
